book_repo: apache/cloudberry-pxf/docs/book

public_host: localhost:9292

sections:
- repository:
    name: content
  directory: pxf/WIP
  subnav_template: pxf-subnav

template_variables:
  book_title: Apache Cloudberry PXF Documentation
  book_title_short:  Apache Cloudberry PXF Docs
  domain_name: cloudberry.apache.org
  product_link: <div class="header-item"><a href="https://docs.cloudberry.apache.org">To Cloudberry Docs</a></div>
  product_url: https://cloudberry.apache.org
  support_call_to_action: <a href="https://cloudberry.apache.org/community/" target="_blank">Need Support?</a>
  support_link: <a href="https://github.com/apache/cloudberry-pxf">GitHub</a>
  support_url: https://cloudberry.apache.org

broken_link_exclusions: iefix|arrowhead
